# Generated by Django 3.2 on 2025-03-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('IOS', '苹果'), ('ANDROID', '安卓')], max_length=10, verbose_name='充值系统')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='充值金额')),
                ('base_currency', models.PositiveIntegerField(verbose_name='基础点券')),
                ('bonus_currency', models.PositiveIntegerField(verbose_name='绑定点券')),
                ('monthly_limit', models.PositiveIntegerField(default=5, verbose_name='每月限购次数')),
            ],
            options={
                'verbose_name': '充值面额',
                'verbose_name_plural': '充值面额',
                'ordering': ['platform', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='GameName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='游戏名称')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level_type', models.CharField(choices=[('CUSTOMER', '消费者等级'), ('SUPPLIER', '供应商等级')], db_index=True, default='CUSTOMER', max_length=16, verbose_name='等级类型')),
                ('title', models.CharField(max_length=32, verbose_name='等级名称')),
                ('percent', models.IntegerField(help_text='0-100整数，如90表示90折', verbose_name='折扣百分比')),
            ],
            options={
                'verbose_name': '用户等级',
                'verbose_name_plural': '用户等级',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=16, verbose_name='姓名')),
                ('usertype', models.CharField(choices=[('SUPERADMIN', '超级管理员'), ('ADMIN', '普通管理员'), ('CUSTOMER', '消费者'), ('SUPPLIER', '供应商'), ('SUPPORT', '客服')], default='CUSTOMER', max_length=32, verbose_name='用户类型')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号码')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userinfo', to='web.level', verbose_name='等级')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='web.userinfo', verbose_name='父级')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('charge_type', models.SmallIntegerField(choices=[(1, '充值'), (2, '扣款'), (3, '创建订单'), (4, '删除订单'), (5, '撤单')], verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='金额')),
                ('order_oid', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='订单号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to='web.userinfo', verbose_name='管理员')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='web.userinfo', verbose_name='客户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('login_ip', models.CharField(max_length=18, verbose_name='登录ip')),
                ('login_city', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录城市')),
                ('login_province', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录省份')),
                ('login_device_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备类型')),
                ('login_os', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统')),
                ('login_browser', models.CharField(blank=True, max_length=64, null=True, verbose_name='浏览器名称')),
                ('map_location', models.CharField(blank=True, max_length=256, null=True, verbose_name='地图定位')),
                ('exact_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='精确地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loginlog', to='web.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_levels', to='web.userinfo', verbose_name='创建者'),
        ),
        migrations.CreateModel(
            name='GameOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('IOS', '苹果'), ('ANDROID', '安卓')], default='ANDROID', max_length=10, verbose_name='充值系统')),
                ('recharge_link', models.URLField(blank=True, null=True, verbose_name='充值链接')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='充值二维码')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '超时'), (4, '撤单')], default=1, verbose_name='订单状态')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumer_orders', to='web.userinfo', verbose_name='订单消费者')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='web.userinfo', verbose_name='订单入库人')),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.gamename', verbose_name='游戏名称')),
                ('recharge_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.gamedenomination', verbose_name='充值选项')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
            },
        ),
        migrations.AddField(
            model_name='gamedenomination',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.gamename', verbose_name='所属游戏'),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('creator', 'title', 'level_type')},
        ),
    ]
