# Generated by Django 3.2 on 2025-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedenomination',
            name='active',
            field=models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='gamedenomination',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='gamedenomination',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
