# Generated by Django 3.2 on 2025-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20250327_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedenomination',
            name='gift_currency',
            field=models.PositiveIntegerField(default=0, help_text='用户获得的额外赠送点券', verbose_name='赠送点券'),
        ),
        migrations.AlterField(
            model_name='gamedenomination',
            name='bonus_currency',
            field=models.PositiveIntegerField(default=0, verbose_name='绑定点券'),
        ),
    ]
