# Generated by Django 3.2 on 2025-03-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20250327_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameorder',
            name='created_at',
        ),
    ]
