# Generated by Django 3.2 on 2025-03-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20250329_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedenomination',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='web.gamename', verbose_name='所属游戏'),
        ),
    ]
