# Generated by Django 3.2 on 2025-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_gamedenomination_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='QV',
            field=models.CharField(default='V区', max_length=10, verbose_name='Q区还是V区'),
        ),
    ]
