# Generated by Django 3.2 on 2025-04-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_gameorder_qv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='QV',
            field=models.CharField(choices=[('Q', 'Q区'), ('V', 'V区')], default='V区', max_length=10, verbose_name='Q区还是V区'),
        ),
    ]
