# Generated by Django 3.2 on 2025-04-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_gameorder_qv'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=10, verbose_name='操作类型')),
                ('changed_fields', models.JSONField(default=dict, verbose_name='变更字段')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='web.gameorder')),
            ],
            options={
                'verbose_name': '订单修改记录',
                'verbose_name_plural': '订单修改记录',
                'ordering': ['-operation_time'],
            },
        ),
    ]
