# Generated by Django 3.2 on 2025-04-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_ordereditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='recharge_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='充值链接'),
        ),
    ]
