# Generated by Django 3.2 on 2025-04-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_gameorder_recharge_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='customer',
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='userinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xxx', to='web.userinfo', verbose_name='当前用户'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('CUSTOMER', '消费者等级'), ('SUPPLIER', '供应商等级'), ('SUPPORT', '客服等级')], db_index=True, default='CUSTOMER', max_length=16, verbose_name='等级类型'),
        ),
    ]
