# Generated by Django 3.2 on 2025-04-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20250402_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='userinfo',
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_userinfo', to='web.userinfo', verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_userinfo', to='web.userinfo', verbose_name='客户'),
        ),
    ]
