# Generated by Django 3.2 on 2025-04-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_transactionrecord_charge_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='order_oid',
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='客服提成金额'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='cross_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='跨圈费用'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_transactions', to='web.userinfo'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='is_cross_circle',
            field=models.BooleanField(default=False, verbose_name='是否跨圈'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='web.gameorder'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='supplier_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='供应商结算'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='support_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='客服垫付款'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='system_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='系统费用'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='t_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='交易编号'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_transactions', to='web.userinfo'),
        ),
        migrations.AddIndex(
            model_name='transactionrecord',
            index=models.Index(fields=['from_user', 'charge_type'], name='web_transac_from_us_f6654b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionrecord',
            index=models.Index(fields=['is_cross_circle', 'created_time'], name='web_transac_is_cros_d3c38c_idx'),
        ),
    ]
