# Generated by Django 3.2 on 2025-04-07 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20250403_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_transactions', to='web.userinfo', verbose_name='入库人圈子管理员'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_transactions', to='web.userinfo', verbose_name='出库人圈子管理员'),
        ),
    ]
