# Generated by Django 3.2 on 2025-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_pricepolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricepolicy',
            name='price',
        ),
        migrations.AddField(
            model_name='pricepolicy',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣'),
        ),
    ]
