# Generated by Django 3.2 on 2025-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20250408_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.CharField(choices=[('recharge', '充值'), ('deduction', '扣款'), ('order_create', '创建订单'), ('order_cancel', '取消订单'), ('order_complete', '完成订单')], max_length=32, verbose_name='类型'),
        ),
    ]
