# Generated by Django 3.2 on 2025-04-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_transactionrecord_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='outed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outed_orders', to='web.userinfo', verbose_name='订单出库人'),
        ),
    ]
