# Generated by Django 3.2 on 2025-04-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_gameorder_outed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='admin_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='管理员付款'),
        ),
    ]
