# Generated by Django 3.2 on 2025-04-12 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_transactionrecord_admin_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-login_time'], 'verbose_name': '登录日志'},
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.CharField(choices=[('recharge', '充值'), ('deduction', '扣款'), ('order_create', '创建订单'), ('order_cancel', '取消订单'), ('order_complete', '完成订单'), ('order_outtime', '超时订单')], max_length=32, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='IPDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=64, verbose_name='服务商')),
                ('detection_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('is_valid', models.BooleanField(default=False, verbose_name='是否有效')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始数据')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='国家')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='地区')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('isp', models.CharField(blank=True, max_length=128, null=True, verbose_name='ISP')),
                ('login_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_detection_results', to='web.loginlog')),
            ],
            options={
                'verbose_name': 'IP检测结果',
                'ordering': ['detection_time'],
            },
        ),
    ]
