# Generated by Django 5.2 on 2025-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20250412_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdetectionresult',
            name='exact_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='精确地址'),
        ),
        migrations.AddField(
            model_name='ipdetectionresult',
            name='map_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='地图链接'),
        ),
    ]
