# Generated by Django 5.2 on 2025-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_ipdetectionresult_exact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='active',
            field=models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
