# Generated by Django 5.2 on 2025-04-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_loginlog_active_loginlog_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '超时'), (4, '删除')], default=1, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='CrossCircleFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(1, '激活'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('finished_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='基于订单金额和借调规则计算得出', max_digits=10, verbose_name='跨圈借调费金额')),
                ('in_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收账款')),
                ('out_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应支出账款')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_cross_fees', to='web.userinfo', verbose_name='借入方管理员（出库人圈子）')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lent_cross_fees', to='web.userinfo', verbose_name='借出方管理员（入库人圈子）')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
