# Generated by Django 5.2 on 2025-04-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_gameorder_order_status_crosscirclefee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crosscirclefee',
            old_name='in_payment',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='crosscirclefee',
            name='out_payment',
        ),
        migrations.AlterField(
            model_name='crosscirclefee',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='基于订单金额和借调规则计算得出', max_digits=10, verbose_name='跨圈借调费金额'),
        ),
    ]
