# Generated by Django 5.2 on 2025-04-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_rename_in_payment_crosscirclefee_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crosscirclefee',
            old_name='fee_amount',
            new_name='crossfee_amount',
        ),
    ]
