# Generated by Django 5.2 on 2025-04-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_rename_fee_amount_crosscirclefee_crossfee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CLEAR', '清空记录'), ('CREATE', '创建记录'), ('UPDATE', '更新记录'), ('DELETE', '删除记录')], default='CLEAR', max_length=10, verbose_name='操作类型')),
                ('action', models.CharField(max_length=255, verbose_name='操作内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联对象类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='web.userinfo', verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'ordering': ['-timestamp'],
            },
        ),
    ]
