# Generated by Django 5.2 on 2025-04-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_operationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlog',
            name='action_type',
        ),
    ]
