# Generated by Django 5.2 on 2025-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_remove_operationlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='is_own_action',
            field=models.BooleanField(default=False, verbose_name='是否本人操作'),
        ),
    ]
