# Generated by Django 5.2 on 2025-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_operationlog_is_own_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='charge_type',
            field=models.CharField(choices=[('recharge', '充值'), ('deduction', '扣款'), ('order_create', '创建订单'), ('order_delete', '删除订单'), ('order_complete', '完成订单'), ('order_outtime', '超时订单')], max_length=32, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='QbSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb', models.IntegerField(verbose_name='QB数量')),
                ('combo', models.CharField(max_length=255, verbose_name='组合')),
                ('points', models.IntegerField(verbose_name='合计点券')),
                ('calculation', models.TextField(verbose_name='计算过程')),
            ],
            options={
                'db_table': 'combinations',
                'indexes': [models.Index(fields=['qb'], name='qb_index')],
                'unique_together': {('qb', 'combo')},
            },
        ),
    ]
