# Generated by Django 5.2 on 2025-04-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_transactionrecord_charge_type_qbsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='creator',
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_userinfo', to='web.userinfo', verbose_name='操作人员'),
        ),
    ]
