# Generated by Django 5.2 on 2025-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_remove_transactionrecord_creator_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionrecord',
            name='web_transac_from_us_f6654b_idx',
        ),
        migrations.RenameField(
            model_name='transactionrecord',
            old_name='from_user',
            new_name='from_admin',
        ),
        migrations.RenameField(
            model_name='transactionrecord',
            old_name='to_user',
            new_name='to_admin',
        ),
        migrations.AddIndex(
            model_name='transactionrecord',
            index=models.Index(fields=['from_admin', 'charge_type'], name='web_transac_from_ad_2bb3a2_idx'),
        ),
    ]
